site_name: UA Capstone Tours

nav:
  - Home: index.md
  - Getting Started: development-guide.md
  - Architecture:
    - Data Model: data-model.md
    - API Reference: api-reference.md
    - Frontend Components: frontend-components.md
  - Deployment:
    - Backend Hosting: backend-hosting-guide.md
    - Frontend Hosting: frontend-hosting-guide.md
  - Project:
    - Team: team.md
    - Deliverables: deliverables.md

docs_dir: docs
