# Generated by Django 5.2.11 on 2026-02-11 01:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(help_text='Brief text for map popups and lists')),
                ('long_description', models.TextField(help_text='Full description shown on the detail page')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Latitude/longitude of the landmark', srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True, help_text='Controls whether this landmark is visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]