# Generated by Django 5.2.11 on 2026-02-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landmark_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='locations_db.landmark')),
            ],
            options={
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
    ]
