# Generated by Django 5.2.13 on 2026-04-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_db', '0002_landmarkphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='category',
            field=models.CharField(choices=[('dining', 'Dining'), ('academic', 'Academic Building'), ('library', 'Library'), ('athletics', 'Athletic Facility'), ('housing', 'Housing'), ('poi', 'Point of Interest'), ('generic', 'Other')], default='generic', help_text='Type of landmark', max_length=20),
        ),
    ]
